//
// Created by 77205 on 2021/8/27.
//

#ifndef OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERACTION_H_
#define OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERACTION_H_

class BaseRenderAction {

};

#endif //OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERACTION_H_
