//
// Created by 77205 on 2021/8/27.
//

#ifndef OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERRESOURCE_H_
#define OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERRESOURCE_H_

class BaseRenderResource {

};

#endif //OUR_GRAPHIC_FRAMEWORK_BACKEND_BASERENDERRESOURCE_H_
